### ISSUE TITLE
--checkconfig doesn't check config

### ISSUE THREAD

**Issue by Michad** [cognusion/go-jar#1]
## Expected Behavior

Running `jard --checkconfig` should validate the configuration is valid and output any issues that would occur when running the same config file through `jard --config`

## Actual Behavior

jard outputs Ok and exits regardless of contents of config file

## Steps to Reproduce the Problem

```
$ cat test.yml
asklfjas
fsa
fasg
jas
jg
asg
sag
asg
asjgn
ewy
weeyw
yeew
$ go-jar/cmd/jard/jard --checkconfig test.yml
Ok
$ go-jar/cmd/jard/jard --config test.yml
2023/07/01 17:47:45 jard.go:27: Error loading config 'test.yml': While parsing config: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `asklfja...` into map[string]interface {}
```

## Specifications

  - Version: JARD 1.1.0+git
  - Platform: CentOS
  - Subsystem:  go1.20.5

**Comment by cognusion** [comment]
Hello! `--checkconfig` is a boolean, so `--checkconfig --config whatever.yml` is what you/re looking for!
